import './globals.css';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';

const font = Plus_Jakarta_Sans({ subsets: ['latin'], preload: true });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body
				className={`bg-LightGrey min-h-screen transition-colors duration-700 dark:bg-VeryDarkGrey ${font.className}`}>
				{children}
			</body>
		</html>
	);
}
